### ISSUE TITLE
ssh with password ask requires a different flavour of ssh to be installed on a Mac

### ISSUE THREAD

**Issue by mayur-raja** [IBM/z_ansible_collections_samples#99] opened 2021-07-28 10:23 UTC
**Describe the bug**
ssh with password ask does not work on the Mac. It returns a message indicating that a different flavour of SSH that supports passwords is required. 

**To Reproduce**
Specify ssh with password ask, as defined in the configuration_guide.md document, on a Mac. If the Mac does not have a flavour of SSH that supports passwords, it fails. One needs to set up ssh that supports passwords to get this to work. However, I did not bother and instead opted to configure passwordless ssh signon. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ddimatos** [comment] 2021-08-13 02:56
@mayur-raja - which version of the `ibm_zos_core` collection are you using? If i understand, this has been resolved in the latest `ibm_zos_core 1.4.0-beta.1` collection.  I believe the issue you are referring is this one [here](https://github.com/ansible-collections/ibm_zos_core/issues/130) and is not related to the playbook repository, it is related to the [ibm_zos_core collection repository](https://github.com/ansible-collections/ibm_zos_core) and resolved. See also release notes [here](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#version-1-4-0-beta-1) 

```
When using the zos_copy or zos_fetch modules in earlier versions of this collection without ‘passwordless’ SSH configured such that you are using --ask-pass or passing an ansible_password in a configuration; during the playbook execution a second password prompt for SFTP would appear pausing the playbook execution. This is resolved in this release.

When using the zos_copy or zos_fetch modules, if you tried to use Ansible connection options such as host_key_checking or port, they were not included as part of the modules execution. This is resolved in this release by ensuring compatibility with the ansible.builtin.ssh plugin options. Refer to the SSH plugin documentation to enable supported options.
```

**Comment by ddimatos** [comment] 2021-08-19 14:59
@mayur-raja - this was accidentally closed, reopened to wait for your response.

**Comment by ddimatos** [comment] 2022-07-12 16:50
@mayur-raja since we were not able to reproduce your issue and not obtain any updates I will close the issue. Feel free to re-open it any time. Also note, this repository issues are for the docs and playbooks that are hosted in this repository, if the issue is related specifically to a collection, please visit those collections repositories and open issues there. 

I am also sharing the[ openSSH docs from ansible](https://docs.ansible.com/ansible/latest/user_guide/connection_details.html) that explain the fallback to paramiko if the openSSH version is backlevel.

**Closed by ddimatos** 2022-07-12 16:50 UTC
Labels: Status: In Progress
